### PR TITLE
fix page reload on accountsChanged

### PR DESCRIPTION
**Pull request by kangarang**
still seeing an issue where the endpoint for checking if
the account has responded to the poll already, but at least
the window refreshing is resolved.

i didn't want to add more state.

### CODE REVIEW

**Comment by akuanti** [comment]
I'm not sure if I understand your comment, but does it correspond to what I'm seeing, where if I change the account from one that has responded to one that has not, it doesn't show the form?

**Comment by kangarang** [comment]
sorry i should have expanded the comment -- the symptom happens during one of the effects, where it calls the api to check whether the account has `alreadyVoted`. it happens twice if the user has not enabled the app.

**Comment by kangarang** [comment]
in my opinion, `/poll` is spaghetti code, and very difficult to make changes to. we should rewrite the whole thing next time panvala has a poll. i propose we close this pr for now

**Comment by kangarang** [comment]
closing due to bad code

**Pull request closed without merging**
