### PR TITLE
Add metadata hash for stake donations

### PR DESCRIPTION
**Pull request by akuanti**
Replace empty hash with IPFS hash for losing slate stake donation metadata.

* Add `losingSlateDonation.json`

### CODE REVIEW

**Comment by akuanti** [comment]
Do not merge yet: I'm going to replace that string assignment with a hex literal of the encoded string.

**Comment by akuanti** [comment]
Okay, disregard that previous comment: the string assignment is equivalent to the hex literal.

```solidity
pragma solidity ^0.5.1;


contract StringBytes {
    function convertString() public pure returns(bytes memory) {
        bytes memory b = "Qmepxeh4KVkyHYgt3vTjmodB5RKZgUEmdohBZ37oKXCUCm";
        return b;
    }
    
    function asBytes() public pure returns(bytes memory) {
        bytes memory hash = hex"516d6570786568344b566b79485967743376546a6d6f644235524b5a6755456d646f68425a33376f4b584355436d";
        return hash;
    }
}
```

**Comment by niran** [comment]
@kangarang Can you point me at the code where you store proposal or slate metadata on chain? I want to verify that you're storing the metadata hashes as strings.

**Comment by kangarang** [comment]
@niran 

grant slates: https://github.com/ConsenSys/panvala/blob/develop/client/pages/slates/create/grant.tsx

gov slates : https://github.com/ConsenSys/panvala/blob/develop/client/utils/transaction.ts

**Comment by kangarang** [comment]
donate: https://github.com/ConsenSys/panvala/blob/develop/client/pages/Donate.tsx

**Pull request merged**
